name: Chai - Build/Test

on:
  push:
  pull_request:

jobs:
  build-test-chai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"          
          "$HOME/.moon/bin/moon" version --all

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            tests/package-lock.json

      - name: Install npm dependencies for 'tests'
        working-directory: tests
        run: npm ci

      - name: Install Moonbit dependencies
        run: moon update

      - name: Type check
        run: |
          moon check --target js
          moon check --target wasm-gc

      - name : Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('tests/package-lock.json') }}
      
      - name: Run Playwright tests
        working-directory: tests
        run: |
          npm ci
          npx playwright install chromium --with-deps

      - name: Build examples
        run: ./scripts/build-example-assets.sh

      - name: Run Tests
        run: ./scripts/test-all.sh

